### ISSUE TITLE
Robotidy 1.5.0 crashes on a dir path

### ISSUE THREAD

**Issue by sergii-tsymbal-exa** [MarketSquare/robotframework-tidy#177]
Robotidy 1.5.0 fails when dir path is provided but works fine on a file path
Did not reproduce on 1.4.0
```
bash-5.1$ robotidy --version
robotidy, version 1.5.0
bash-5.1$ robotidy robot/exa-end2end-tests/tests/cloud_archive_ui/
Traceback (most recent call last):
  File "/Users/sergiitsymbal/robot/bin/robotidy", line 8, in <module>
    sys.exit(cli())
  File "/Users/sergiitsymbal/robot/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sergiitsymbal/robot/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/sergiitsymbal/robot/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sergiitsymbal/robot/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/sergiitsymbal/robot/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/sergiitsymbal/robot/lib/python3.8/site-packages/robotidy/cli.py", line 386, in cli
    tidy = Robotidy(
  File "/Users/sergiitsymbal/robot/lib/python3.8/site-packages/robotidy/app.py", line 35, in __init__
    self.sources = get_paths(src, exclude, extend_exclude)
  File "/Users/sergiitsymbal/robot/lib/python3.8/site-packages/robotidy/files.py", line 107, in get_paths
    sources.update(iterate_dir((path,), exclude, extend_exclude, gitignore))
  File "/Users/sergiitsymbal/robot/lib/python3.8/site-packages/robotidy/files.py", line 125, in iterate_dir
    gitignore + get_gitignore(path) if gitignore is not None else None
TypeError: unsupported operand type(s) for +: 'PathSpec' and 'PathSpec'
bash-5.1$ robotidy robot/exa-end2end-tests/tests/cloud_archive_ui/saas_ui_cloud_archive_check.robot 
bash-5.1$ 
```

**Comment by bhirsz** [comment]
Thank you for the report. I can't replicate it - it could be related to your repository structure. While I'm trying different settings, can you answer following:

Are you using more than one .gitignore in your repository? 
Are you using Linux?

**Comment by bhirsz** [comment]
I can replicate it with pathspec==0.8.0, but not with 0.8.1. If it's also the case for you, I will release Robotdy fix version with ugpraded dependency version.

**Comment by sergii-tsymbal-exa** [comment]
@bhirsz I am using macos. The issue reproduces even without gitignore files
Found the cause: reproduces with `pathspec==0.8.0`, notrep with `pathspec==0.9.0`.  A minimal version should be updated in `setup.py`
