### ISSUE TITLE
Fatal exception occurred with NormalizeSeparators on file with pipes

### ISSUE THREAD

**Issue by glueologist** [MarketSquare/robotframework-tidy#390]
Running robotidy over a set of test case files and got a fatal exception occurred.  

After tracking down file causing error tested with single file run and see the same failure

Cmd:

```
robotidy --output outbad.robot --separator space --transform  NormalizeSeparators bad.robot
```

bad.robot:
```
*** Settings ***
| Resource | geist_toucan_keywords.robot


*** Variables ***
| ${max pages}  | 100
| ${geist type} | PDU


*** Test Cases ***
Repeatedly Login And Then Close
| | ${type}= | Convert To Lowercase | ${geist type}
| | @{pages}= | Set Variable If | '${type}'=='pdu' | ${PDU SYSTEM PAGES}
| | @{pages}= | Set Variable If | '${type}'=='env' | ${ALL BB ENV TOUCAN PAGES}
| | Log To Console | \n
| | FOR | ${index} | IN RANGE | ${max pages}
| |     | ${num}= | Generate Random String | 1 | [NUMBERS]
| |     | ${idx}= | Convert To Integer | ${num}
| |     | ${page name}= | Set Variable | ${pages}[${idx}]
| |     | Log To Console | ${page name}
| |     | Login To Toucan App
| |     | Go To Toucan Page | ${page name}
| | [Teardown] | Close Browser
```

Error output:
```
Traceback (most recent call last):
  File "/home/phawkins/devel/work/test-automation/rf_venv/bin/robotidy", line 8, in <module>
    sys.exit(cli())
  File "/home/phawkins/devel/work/test-automation/rf_venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/phawkins/devel/work/test-automation/rf_venv/lib/python3.8/site-packages/rich_click/rich_command.py", line 19, in main
    return super().main(*args, standalone_mode=False, **kwargs)
  File "/home/phawkins/devel/work/test-automation/rf_venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/phawkins/devel/work/test-automation/rf_venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/phawkins/devel/work/test-automation/rf_venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/phawkins/devel/work/test-automation/rf_venv/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/phawkins/devel/work/test-automation/rf_venv/lib/python3.8/site-packages/robotidy/decorators.py", line 44, in wrapper
    raise err
  File "/home/phawkins/devel/work/test-automation/rf_venv/lib/python3.8/site-packages/robotidy/decorators.py", line 27, in wrapper
    return func(*args, **kwargs)
  File "/home/phawkins/devel/work/test-automation/rf_venv/lib/python3.8/site-packages/robotidy/cli.py", line 521, in cli
    status = tidy.transform_files()
  File "/home/phawkins/devel/work/test-automation/rf_venv/lib/python3.8/site-packages/robotidy/app.py", line 49, in transform_files
    diff, old_model, new_model = self.transform(model, disabler_finder.disablers)
  File "/home/phawkins/devel/work/test-automation/rf_venv/lib/python3.8/site-packages/robotidy/app.py", line 70, in transform
    transformer.visit(model)
  File "/home/phawkins/devel/work/test-automation/rf_venv/lib/python3.8/site-packages/robot/parsing/model/visitor.py", line 62, in visit
    return visitor(node)
  File "/home/phawkins/devel/work/test-automation/rf_venv/lib/python3.8/site-packages/robotidy/transformers/NormalizeSeparators.py", line 62, in visit_File
    return self.generic_visit(node)
  File "/usr/lib/python3.8/ast.py", line 447, in generic_visit
    value = self.visit(value)
  File "/home/phawkins/devel/work/test-automation/rf_venv/lib/python3.8/site-packages/robot/parsing/model/visitor.py", line 62, in visit
    return visitor(node)
  File "/home/phawkins/devel/work/test-automation/rf_venv/lib/python3.8/site-packages/robotidy/disablers.py", line 36, in wrapper
    return func(self, node, *args, **kwargs)
  File "/home/phawkins/devel/work/test-automation/rf_venv/lib/python3.8/site-packages/robotidy/transformers/NormalizeSeparators.py", line 87, in visit_TestCaseSection
    return self.should_visit("testcases", node)
  File "/home/phawkins/devel/work/test-automation/rf_venv/lib/python3.8/site-packages/robotidy/transformers/NormalizeSeparators.py", line 66, in should_visit
    return self.generic_visit(node)
  File "/usr/lib/python3.8/ast.py", line 447, in generic_visit
    value = self.visit(value)
  File "/home/phawkins/devel/work/test-automation/rf_venv/lib/python3.8/site-packages/robot/parsing/model/visitor.py", line 62, in visit
    return visitor(node)
  File "/home/phawkins/devel/work/test-automation/rf_venv/lib/python3.8/site-packages/robotidy/transformers/NormalizeSeparators.py", line 97, in visit_TestCase
    return self.indented_block(node)
  File "/home/phawkins/devel/work/test-automation/rf_venv/lib/python3.8/site-packages/robotidy/transformers/NormalizeSeparators.py", line 92, in indented_block
    node.body = [self.visit(item) for item in node.body]
  File "/home/phawkins/devel/work/test-automation/rf_venv/lib/python3.8/site-packages/robotidy/transformers/NormalizeSeparators.py", line 92, in <listcomp>
    node.body = [self.visit(item) for item in node.body]
  File "/home/phawkins/devel/work/test-automation/rf_venv/lib/python3.8/site-packages/robot/parsing/model/visitor.py", line 62, in visit
    return visitor(node)
  File "/home/phawkins/devel/work/test-automation/rf_venv/lib/python3.8/site-packages/robotidy/transformers/NormalizeSeparators.py", line 103, in visit_For
    self.visit_Statement(node.end)
  File "/home/phawkins/devel/work/test-automation/rf_venv/lib/python3.8/site-packages/robotidy/disablers.py", line 19, in wrapper
    return func(self, node, *args, **kwargs)
  File "/home/phawkins/devel/work/test-automation/rf_venv/lib/python3.8/site-packages/robotidy/transformers/NormalizeSeparators.py", line 147, in visit_Statement
    has_pipes = statement.tokens[0].value.startswith("|")
AttributeError: 'NoneType' object has no attribute 'tokens'
Fatal exception occurred. You can create an issue at https://github.com/MarketSquare/robotframework-tidy/issues . Thanks!

```

**Comment by bhirsz** [comment]
It looks the problem originated not in Robotidy but Robot Framework core parsing - visit_Statement should not receive None. Nonetheless we need to handle such a case, I will check which code is giving us 'None' and I will update the visit method to cover it.

**Comment by bhirsz** [comment]
Missing ``END`` in FOR loop is the culprit (but of course it shouldn't trip NormalizeSeparator).

**Comment by glueologist** [comment]
Yea, I did some troubleshooting and realized the FOR loop was mal-formed.  Thx.
