### ISSUE TITLE
Robotidy to support Robot Framework 7.0 releases

### ISSUE THREAD

**Issue by ssallmen** [MarketSquare/robotframework-tidy#614]
Currently Robotidy (4.7.0) seems not to support Robot Framework 7.0 releases (or atleast 7.0rc1). It is still a release candidate but wanted to open this issue to bring this issue up and hopefully to get a Robotidy version that supports also the upcoming RF 7.0 version.

The failure looks like this at the moment (with robotidy 4.7.0) when robotframework 7.0rc1 is installed:
```
PS C:\test> robotidy --config pyproject.toml .
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\test\.venv\Scripts\robotidy.EXE\__main__.py", line 7, in <module>
  File "C:\test\.venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\test\.venv\Lib\site-packages\rich_click\rich_command.py", line 19, in main
    rv = super().main(*args, standalone_mode=False, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\test\.venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\test\.venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\test\.venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\test\.venv\Lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\test\.venv\Lib\site-packages\robotidy\decorators.py", line 30, in wrapper
    raise err
  File "C:\test\.venv\Lib\site-packages\robotidy\decorators.py", line 21, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\test\.venv\Lib\site-packages\robotidy\cli.py", line 480, in cli
    global_config = config_module.MainConfig(cli_config)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\test\.venv\Lib\site-packages\robotidy\config.py", line 228, in __init__
    self.default_loaded = Config.from_raw_config(self.default)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\test\.venv\Lib\site-packages\robotidy\config.py", line 381, in from_raw_config
    return cls(
           ^^^^
  File "C:\test\.venv\Lib\site-packages\robotidy\config.py", line 323, in __init__
    self.load_transformers(transformers_config, force_order, target_version, skip)
  File "C:\test\.venv\Lib\site-packages\robotidy\config.py", line 402, in load_transformers
    transformers = load_transformers(
                   ^^^^^^^^^^^^^^^^^^
  File "C:\test\.venv\Lib\site-packages\robotidy\transformers\__init__.py", line 480, in load_transformers
    for container in import_transformer(name, transformers_config, skip):
  File "C:\test\.venv\Lib\site-packages\robotidy\transformers\__init__.py", line 324, in import_transformer
    yield create_transformer_instance(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\test\.venv\Lib\site-packages\robotidy\transformers\__init__.py", line 346, in create_transformer_instance
    positional, named, argument_names = resolve_args(short_name, spec, args, skip, handles_skip=handles_skip)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\test\.venv\Lib\site-packages\robotidy\transformers\__init__.py", line 424, in resolve_args
    argument_names = resolve_argument_names(spec.argument_names, handles_skip)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\test\.venv\Lib\site-packages\robotidy\transformers\__init__.py", line 368, in resolve_argument_names
    return new_args + argument_names
           ~~~~~~~~~^~~~~~~~~~~~~~~~
TypeError: can only concatenate list (not "tuple") to list
Fatal exception occurred. You can create an issue at https://github.com/MarketSquare/robotframework-tidy/issues . Thanks!
```

**Comment by bhirsz** [comment]
Thanks for the issue - this particular problem was reported to me via slack few days ago and I already fixed it on master branch. I'm currently in middle of heavy updates for both Robotidy & Robocop and I plan to release both by end of the year/New Year (and definietely before 7.0 release).

**Comment by ssallmen** [comment]
Thanks for the status update. And thanks for the Robocop update! I just updated to the latest release version of Robocop (4.2.2) and it was enough for me to get Robocop working on my codebase with RF 7.0rc1.

Good work! Happy New Year!
