### ISSUE TITLE
Robot Tidy check failed 

### ISSUE THREAD

**Issue by Lauranlin** [MarketSquare/robotframework-tidy#633]
When I execute the pre-commit, I encounter issues

```
Loading .env environment variables...
check for added large files..............................................Passed
check for merge conflicts................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
black................................................(no files to check)Skipped
flake8...............................................(no files to check)Skipped
isort (python).......................................(no files to check)Skipped
robotidy.................................................................Failed
- hook id: robotidy
- exit code: 1
.......
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\3084\.cache\pre-commit\repo07w66a4h\py_env-python3.9\Scripts\robotidy.EXE\__main__.py", line 7, in <module>
  File "C:\Users\3084\.cache\pre-commit\repo07w66a4h\py_env-python3.9\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\3084\.cache\pre-commit\repo07w66a4h\py_env-python3.9\lib\site-packages\rich_click\rich_command.py", line 19, in main
    return super().main(*args, standalone_mode=False, **kwargs)
  File "C:\Users\3084\.cache\pre-commit\repo07w66a4h\py_env-python3.9\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\3084\.cache\pre-commit\repo07w66a4h\py_env-python3.9\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\3084\.cache\pre-commit\repo07w66a4h\py_env-python3.9\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\3084\.cache\pre-commit\repo07w66a4h\py_env-python3.9\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\3084\.cache\pre-commit\repo07w66a4h\py_env-python3.9\lib\site-packages\robotidy\decorators.py", line 34, in wrapper
    raise err
  File "C:\Users\3084\.cache\pre-commit\repo07w66a4h\py_env-python3.9\lib\site-packages\robotidy\decorators.py", line 22, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\3084\.cache\pre-commit\repo07w66a4h\py_env-python3.9\lib\site-packages\robotidy\cli.py", line 511, in cli
    config = Config(
  File "C:\Users\3084\.cache\pre-commit\repo07w66a4h\py_env-python3.9\lib\site-packages\robotidy\config.py", line 91, in __init__
    self.transformers = self.get_transformers_instances(
  File "C:\Users\3084\.cache\pre-commit\repo07w66a4h\py_env-python3.9\lib\site-packages\robotidy\config.py", line 105, in get_transformers_instances
    for transformer in load_transformers(
  File "C:\Users\3084\.cache\pre-commit\repo07w66a4h\py_env-python3.9\lib\site-packages\robotidy\transformers\__init__.py", line 331, in load_transformers
    container = load_transformer(name, args, skip)
  File "C:\Users\3084\.cache\pre-commit\repo07w66a4h\py_env-python3.9\lib\site-packages\robotidy\transformers\__init__.py", line 239, in load_transformer
    return import_transformer(import_name, args, skip)
  File "C:\Users\3084\.cache\pre-commit\repo07w66a4h\py_env-python3.9\lib\site-packages\robotidy\transformers\__init__.py", line 127, in import_transformer
    positional, named, argument_names = resolve_args(short_name, spec, args, skip, handles_skip=handles_skip)
  File "C:\Users\3084\.cache\pre-commit\repo07w66a4h\py_env-python3.9\lib\site-packages\robotidy\transformers\__init__.py", line 218, in resolve_args
    argument_names = resolve_argument_names(spec.argument_names, handles_skip)
  File "C:\Users\3084\.cache\pre-commit\repo07w66a4h\py_env-python3.9\lib\site-packages\robotidy\transformers\__init__.py", line 162, in resolve_argument_names
    return new_args + argument_names
TypeError: can only concatenate list (not "tuple") to list
Fatal exception occurred.
```

<img width="755" alt="8B711841-E7FD-4612-BDF1-D0462830561E" src="https://github.com/MarketSquare/robotframework-tidy/assets/26050280/bf69abb9-c725-420f-b5d8-8dadc79e546c">

**Comment by bhirsz** [comment]
What Robotidy version are you using? This issue was fixed few releases ago - can you try to install newest version and retest it?

**Comment by Lauranlin** [comment]
I don't know how to check it. I guess it's the latest one. If I clean the cache, it will re-install the pre-commit from the github.

**Comment by Lauranlin** [comment]
Finally, I fixed it by changing the code in .cache/pre-commit according the error printout.
The operation  list + tuple is not allowed.
I convert the list(new_args) to tuple and it works.
.\.cache\pre-commit\repo07w66a4h\py_env-python3.9\Lib\site-packages\robotidy\transformers\__init__.py
![image](https://github.com/MarketSquare/robotframework-tidy/assets/26050280/8d3c50dd-5594-4b3b-8415-7b9304fe7b9d)

**Comment by Lauranlin** [comment]
It's true that the type of new_args and argument_names are not the same.
`print argument_names:
Value:  ()
Type is:  <class 'tuple'>
print new_args:
Value:  ['enabled']
Type is:  <class 'list'>`

**Comment by Lauranlin** [comment]
Hello,

**Comment by bhirsz** [comment]
> Finally, I fixed it by changing the code in .cache/pre-commit according the error printout. The operation list + tuple is not allowed. I convert the list(new_args) to tuple and it works. ..cache\pre-commit\repo07w66a4h\py_env-python3.9\Lib\site-packages\robotidy\transformers__init__.py ![image](https://private-user-images.githubusercontent.com/26050280/301789956-8d3c50dd-5594-4b3b-8415-7b9304fe7b9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4OTA0NzgsIm5iZiI6MTcwNjg5MDE3OCwicGF0aCI6Ii8yNjA1MDI4MC8zMDE3ODk5NTYtOGQzYzUwZGQtNTU5NC00YjNiLTg0MTUtN2I5MzA0ZmU3YjlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDE2MDkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMThkNWU2YjA2NTlkMjk4MGM5NWUwMjAwYmM4ODU5YzhjMTU1M2Q1NmRkYjUxMDYwYjk5M2ZkYWYxNjY4NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PmPG0YpCEIA22m5rQdRuQ9kRKx1p57J-KcaRj-HRrME)

You fixed it in your local installation (which is fine I guess) but robotidy version you're using is quite old. This fix is already included in higher version. Since you're using precommit (it seems so) then you can update version by specyfing it in the .pre-commit-config.yml file in the root of your project - look for ``rev`` parameter. Most recent version is 4.8.1
